apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-reencode
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/franchyze923/frans-homelab.git
    targetRevision: main
    path: gitops/workloads/media-reencode
  destination:
    server: https://kubernetes.default.svc
    namespace: media-reencode
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
