apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/franchyze923/app-of-apps-demo.git
    targetRevision: main
    path: workloads/sabnzbd
  destination:
    server: https://kubernetes.default.svc
    namespace: sabnzbd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
